package main

import (
	"fmt"

	"github.com/seuscode/bill-sdk-go/v2/api/afip"
	"github.com/seuscode/bill-sdk-go/v2/models/afip/aliquot"
	"github.com/seuscode/bill-sdk-go/v2/models/afip/invoice"
	"github.com/seuscode/bill-sdk-go/v2/models/afip/payment_method"
	"github.com/seuscode/bill-sdk-go/v2/models/api"
)

func main() {
	afip, err := afip.NewAfipManager(afip.AfipOptions{
		ApiKey:     "YOUR_API_KEY",
		Enviroment: api.PRODUCTION,
		Language:   api.ENGLISH,
	})

	if err != nil {
		panic(err)
	}

	filePath, err := afip.EBilling.GenerateInvoicePDF(invoice.GenerateInvoicePDFRequest{
		InvoiceMetaData: invoice.InvoiceMetaData{
			PaymentMethod:            payment_method.Cash,
			ClientPhone:              "+5491234567890",
			ClientEmail:              "example@email.com",
			ClientAddress:            "Some Address, Some City, Some Province",
			ClientFiscalType:         invoice.CONSUMIDOR_FINAL,
			ClientNameOrBusinessName: "Some Name or Business Name",
		},
		InvoiceData: invoice.IssueInvoiceResponse{
			CAE:        "75010562627746",
			CAEFchVto:  "20250115",
			CbteFch:    "20250105",
			CbteTipo:   int32(invoice.FACTURA_B),
			PtoVta:     7,
			CbteNro:    51054,
			Concepto:   1,
			DocTipo:    99,
			DocNro:     0,
			ImpIVA:     18.24,
			ImpNeto:    173.68,
			ImpOpEx:    0,
			ImpTotal:   191.92,
			ImpTotConc: 0,
			ImpTrib:    0,
			MonCotiz:   1,
			IVAs: []invoice.InvoiceTax{
				{
					Id:      4,
					BaseImp: 173.68,
					Importe: 18.24,
				},
			},
		},
		InvoiceProducts: []invoice.InvoiceItem{
			{
				Id:       "1",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "2",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "3",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "4",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "5",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "6",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "7",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "8",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "9",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "10",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "11",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "12",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "13",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "14",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "15",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "16",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "17",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "18",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "19",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "20",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "gssss",
				Subtotal: -41.32,
			},
			{
				Id:       "1",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "2",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "3",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "4",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "5",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "6",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "7",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "8",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "9",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "10",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "11",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "12",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "13",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "14",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "15",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "16",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "17",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "18",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "Descuento",
				Subtotal: -41.32,
			},
			{
				Id:       "19",
				Cantidad: 4.3,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   50,
				Desc:     "Vacio",
				Subtotal: 215,
			},
			{
				Id:       "20",
				Cantidad: 1,
				Iva:      aliquot.TenDotFivePercent,
				Precio:   -41.32,
				Desc:     "gssss",
				Subtotal: -41.32,
			},
		},
	}, "examples/generate-pdf/invoice", "test_invoice.pdf")

	if err != nil {
		panic(err)
	}

	fmt.Println(filePath)
}
